### ISSUE TITLE
Header row has too many columns

### ISSUE THREAD

**Issue by austinmeier** [jhpoelen/samara#17]
I just noticed that when I split the resulting Grin.tsv file using tabs, I end up with 25 columns in the header row...  as opposed to the 13 in the data rows.  Might be a formatting thing.   I looked into it, and I cannot seem to figure out why it's happening.  

Command I was using:  cat newest_GRIN_scrape.tsv |awk '{FS="\t";print NF}'

**Comment by jhpoelen** [comment]
Interesting!

I took a look at the grin-16k.tsv.gz related to release 0.1.3 counted expected amount of tabs tabs (see below, ```^I``` are tabs). Also, the file opened ok in LibreOffice spreadsheet with tab separator.

```
$ cat -t grin-16k.csv | head -n 1
taxon id^Itaxon name^Idescriptor id^Idescriptor name^Idescriptor definition^Imethod id^Imethod name^Iobserved value^Iaccession id^Iaccession number^Iaccession name^Icollected from^Icitations
```

This makes me suspect that awk is counting too many field separators in the header file.

Please confirm that you can reproduce my findings.

**Comment by austinmeier** [comment]
Can confirm your findings.  I also opened the file with Textwrangler, and saw that there were the correct number of tabs in the header row before posting this issue.  I can't explain why awk is having this issue.

**Comment by jhpoelen** [comment]
Thanks for checking. Suggest to close issue.
