### ISSUE TITLE
introduce grin identifiers to facilitate in term mappings

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/samara#18]
@cmungall suggested to introduce a grin id prefix in preparation for (non-trivial) terms mapping to TO / NCBITaxon etc.

Here's my suggestion for prefixes:

term | prefix | example | url
--- | --- | --- | ---
GRIN taxon id | GRINTaxon: | GRINTaxon:300359 | https://npgsweb.ars-grin.gov/gringlobal/taxonomydetail.aspx?id=300359
GRIN descriptor id | GRINDesc: | GRINDesc:68104 | https://npgsweb.ars-grin.gov/gringlobal/descriptordetail.aspx?id=68104
GRIN method id | GRINMethod: | GRINMethod:391002 | https://npgsweb.ars-grin.gov/gringlobal/method.aspx?id=391002
GRIN accession id | GRINAccess: | GRINAccess:1140225 | https://npgsweb.ars-grin.gov/gringlobal/AccessionDetail.aspx?id=1140225

@austinmeyer @cmungall curious to hear your thoughts.

**Comment by cmungall** [comment]
Sounds good. We should use CURIEs for compatibility with the planteome 
system

I suggest a prefix convention

GRINTaxon:
GRINDesc:

etc

**Comment by jhpoelen** [comment]
@cmungall updated example in issue text to reflect this. 

@austinmeier an comments on the prefixes?

**Comment by austinmeier** [comment]
Looks good to me!

**Comment by jhpoelen** [comment]
prefixes will now appear in grin scrape output tsv.
