### ISSUE TITLE
descriptor name does not match descriptor id and definition

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/samara#20]
It appears that descriptor names in GRIN scrape do not correspond to associated descriptor id and definitions.

For example the line:

```GRINTaxon:104918        Medicago sativa L. subsp. falcata (L.) Arcang.  GRINDesc:68104  Winter injury (WINTERINJ)       In-vitro dry matter disappearance (ivdmd) expressed as a percent of the cultivar venal.  Higher than 100% suggests low digestibility & higher by-pass protein.  GRINMethod:391002       ALFALFA.PROTBYPASS.93.VOLENEC   79      GRINAccess:1305140      PI 405064```

has ```Winter injury (WINTERINJ)``` as descriptor name for GRINDesc:68104 and definition ``` In-vitro dry matter disappearance (ivdmd) expressed as a percent of the cultivar venal.  Higher than 100% suggests low digestibility & higher by-pass protein.```. 

Expected is that  GRINDesc:68104 has descriptor name ```By pass protein (PROTBYPASS)```

@austinmeier hope this helps . . . also, can you send me the full grin scrape that you did on your infrastructure?

**Comment by austinmeier** [comment]
Correct.  GRINDesc:68001 (https://npgsweb.ars-grin.gov/gringlobal/descriptordetail.aspx?id=68001) shares data rows with 28 different Descriptor names:  
100 Seed weight in grams (SEEDWGT)
Acid soil tolerance (ACIDSOIL)
Core subset (CORE)
Crown bud number (CRWNBUDNUM)
Crown origin (CROWNORIG)
Days to maturity (DAYSMAT)
Determinate taproot percentage (DETTAPPERC)
Determinate taproot position (DETTAPPOS)
Fibrous root mass (FIBRTMASS)
Flower color (FLOWCOLOR)
Frost damage (FROSTDAM)
Image/picture_1 (IMAGE_1)
L.
Leaf acid detergent fiber (ADFLEAF)
Leaf neutral detergent fiber (NDFLEAF)
Leaf size (LEAFSIZE)
Maturity (MATURITY)
Salt germination - ic(50) valu (SALTGERM)
Secondary root number (ROOTNUM2)
Secondary root position (ROOTPOS2)
Seedling year yield (SDLGYRYLD)
Seed productivity (SEEDPROD)
Stem acid detergent fiber (ADFSTEM)
Stem leaf ratio (STEMLFRAT)
Stem neutral detergent fiber (NDFSTEM)
Tolerance to salt stress (SALTSTRESS)
Unifoliate internode length (UILENGTH)
Winter injury (WINTERINJ)
