### ISSUE TITLE
add source citation apsnet

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/samara#23]
Currently, no source is specified in samara's scrape of APSNET

Desired is to make the data source explicit and provide citation by appending something like

... | sourceCitation | sourceUrl | accessedAt 
--- | --- | --- | ---
... | Wick, R., & Dicklow, B. (2000). Diseases of African Daisy(Gerbera jamesonii H. Bolus ex J. D. Hook). Retrieved August 03, 2016, from http://www.apsnet.org/publications/commonnames/Pages/AfricanDaisy.aspx | http://www.apsnet.org/publications/commonnames/Pages/AfricanDaisy.aspx | 2016-08-03

@austinmeier Any suggestions for the citation format?

**Comment by jhpoelen** [comment]
Took path of least resistance at found that citations like:
```R. Wick and B. Dicklow, primary collators (last update 4/11/00).  Diseases of African Daisy (Gerbera jamesonii H. Bolus ex J. D. Hook). The American Phytopathological Society. Accessed on 2016-08-03 at http://www.apsnet.org/publications/commonnames/Pages/AfricanDaisy.aspx``` are pretty easy to generate. 

Please feel free to re-open / comment if changes are desired.

**Comment by austinmeier** [comment]
I think that'll work just fine. If it needs to be changed, we can deal with that later. Thanks
