### ISSUE TITLE
parse list of genus/species pathogens into separate interactions

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/samara#26]
Some names mentioned in apsnet (e.g. Genus Allexivirus; Garlic viruses A-D (GVA, GVB, GVC, GVD), Garlic virus X (GVX), Garlic mite-borne mosaic virus (GMbMV), Shallot virus X (ShVX) from http://www.apsnet.org/publications/commonnames/Pages/OnionandGarlic.aspx) are actually lists of species of a specific genus. 

Currently the list is interpreted as a single taxon. 

Desired is to parse the list such that species (and their genus) are separated line by line.

So, Genus Allexivirus; Garlic viruses A-D (GVA, GVB, GVC, GVD), Garlic virus X (GVX), Garlic mite-borne mosaic virus (GMbMV), Shallot virus X (ShVX) would turn into:

 Genus | Species 
 --- | ---
Allexivirus | Garlic viruses A-D (GVA, GVB, GVC, GVD)
Allexivirus | Garlic virus X (GVX), 
Allexivirus | Garlic mite-borne mosaic virus (GMbMV)
Allexivirus | Shallot virus X (ShVX)

@austinmeier please advise

**Comment by jhpoelen** [comment]
a possibly more flexible approach would be to represent the taxa as:

taxon path | taxon rank
--- | ---
Allexivirus ```|``` Garlic viruses A-D (GVA, GVB, GVC, GVD) | genus ```|``` species
Allexivirus ```|``` Garlic viruses X | genus ```|``` species
... | ...

**Comment by austinmeier** [comment]
I believe each of those viruses would be considered their own disease.  Thus it would be crucial to have them on their own line.  I'm not sure if there are other lines in which multiple species/genus are listed as causal agents of the same disease.  Either way, so long as the disease name is the same on lines with individual causal agents, we should be fine.

**Comment by jhpoelen** [comment]
Ok. I fixed issue by taking most specific name and expand in multiple lines.

**Comment by jhpoelen** [comment]
Note that for exceptions like ```Garlic viruses A-D```, I've added explicit entries into [apsnetNameMap.tsv](../blob/master/src/main/resources/org/planteome/samara/apsnetNameMap.tsv)

with ```Garlic virusses A-B``` -> ```Garlic virus A|Garlic virus B|Garlic virus C|Garlic virus D```
