### ISSUE TITLE
ars-grin jenkins job fails after upgrade to scala 2.12

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/samara#32]
Scrape job setup at https://build.berkeleybop.org/job/extract-grin-traits/23/console failed due to change in scala version. @cmungall any chance you can update the start script to ```java -jar 'target/scala-2.12/samara-assembly-*.jar' scrape grin``` ?

snippet from jenkins console:
```
+ java -jar 'target/scala-2.11/samara-assembly-*.jar' scrape grin
Error: Unable to access jarfile target/scala-2.11/samara-assembly-*.jar
Build step 'Execute shell' marked build as failure
```

**Comment by jhpoelen** [comment]
PS Same applies to https://build.berkeleybop.org/job/extract-apsnet-diseases

**Comment by jhpoelen** [comment]
@cmungall @austinmeier I was wondering whether it might be pragmatic to give me access to planteome build jobs. . . don't want to keep bugging you about trivial issues and sit around idle while waiting.

**Comment by cmungall** [comment]
I made the changes, I'll chat with @kltm tomorrow about getting you set up

**Comment by jhpoelen** [comment]
Thanks for making the changes, looks like the job are now running again. apsnet completed, ars-grin scrape is in progress as I write.
