### ISSUE TITLE
strange (incorrect) mappings of pathogens in APS

### ISSUE THREAD

**Issue by austinmeier** [jhpoelen/samara#50]
We have found a few oddities in the name matchings for the APS scrape.  Some of the pathogens are being identified as "EST" from NCBI.  An example will help illustrate this:

mapped pathogen:  NCBITaxon:1585532 (Beta vulgaris/Cercospora beticola mixed EST library)

The verbatim name:  Beet curly top virus (BCTV)

The correct pathogen:  NCBITaxon:10840  (Beet curly top virus)

It appears to me that the algorithm is being greedy in some way, and stopping after recognizing "Beet" and mapping to beet (Beta vulgaris)  But I have no idea why it maps to the mixed EST library, instead of mapping to just plain beet.

Here is the offending line from the scrape:

`Curly top	Beet curly top virus (BCTV)	Beet curly top virus (BCTV)	NCBITaxon:1585532	pathogen of	http://purl.obolibrary.org/obo/RO_0002556	Diseases of Cucurbits (Citrullus spp., Cucumis spp., Cucurbita spp., and others)	Citrullus spp., Cucumis spp., Cucurbita spp., and  s	NCBITaxon:3653	R. D. Martyn, M. E. Miller and B. D. Bruton, primary collators (last update 2/19/93). Diseases of Cucurbits (Citrullus spp., Cucumis spp., Cucurbita spp., and others). The American Phytopathological Society. Accessed on 2016-09-07 at http://www.apsnet.org/publications/commonnames/Pages/Curcubits.aspx	http://www.apsnet.org/publications/commonnames/Pages/Curcubits.aspx	2016-09-07`

**Comment by jhpoelen** [comment]
Thanks for sharing this specific example. 

You are correct that GloBI's (old) taxon mapping algorithm was greedy, chopping off terms until a single word remained (now the matching is a bit less greedy). This caused  Beet curly top virus (BCTV) to be chopped off to Beet, which was then mapped to "Beta". Resolving "Beta" via https://resolver.globalnames.org results in an exact canonical match to ncbi taxon 1585532 . https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1585532 . This dubious NCBI matching is known to occur via globalnames.org and I've reported an example of this via https://github.com/GlobalNamesArchitecture/gni/issues/48 which led to   https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1585532 .

**Comment by jhpoelen** [comment]
@austinmeier I've added correct mappings for the terms in https://github.com/jhpoelen/samara/commit/0a263758e21285c91dcdf7b77bbb2df2c5d3746b . Please review. These should be applied on the next aps scrape. Leaving issue open until we can verify this is actually the case.

**Comment by jhpoelen** [comment]
I just ran a apsnet scrape and found that the mapping added via https://github.com/jhpoelen/samara/commit/0a263758e21285c91dcdf7b77bbb2df2c5d3746b are now being applied.

@austinmeier @marieALaporte please continue to add mapping corrections to the files in https://github.com/jhpoelen/samara/tree/master/src/main/resources/org/planteome/samara/apsnet .  This would include PO/taxon mappings .

**Comment by austinmeier** [comment]
So I think there might be an issue with a blanket remapping using the taxonmap.tsv...

There are two places an NCBITaxon:ID shows up, HOST, or PATHOGEN.  In cases of host being assigned an "EST" taxon, it is as simple as just using the plant portion of the EST.  There are actually only 3 examples, and the `host_label` is in 1:1 agreement with the 'host' ID

```
NCBITaxon:331356 - Triticum spp. L.
NCBITaxon:910407 -  Brassica
NCBITaxon:69324 - Gossypium spp.
```

However, in the case of pathogen mappings from these EST taxons, we see more that are just incorrect.  And most importantly: the mappings are not 1:1.  Here is an example of a single NCBITaxon:ID being mapped to multiple `pathogen_label`s

```
NCBITaxon:176297 - Maize chlorotic dwarf virus (MCDV)
NCBITaxon:176297 - Maize chlorotic mottle virus (MCMV)
NCBITaxon:176297 - Maize leaf fleck virus (MLFV)
NCBITaxon:176297 - Maize line virus (MLV)
NCBITaxon:176297 - Maize mosaic virus (MMV)
NCBITaxon:176297 - Maize pellucid ringspot virus (MPRV)
NCBITaxon:176297 - Maize rayado fino virus (MRFV)
NCBITaxon:176297 - Maize red stripe virus (MRSV)
NCBITaxon:176297 - Maize ring mottle virus (MRMV)
NCBITaxon:176297 - Maize rough dwarf virus (MRDV)
NCBITaxon:176297 - Maize sterile stunt virus (strains of barley yellow striate virus)
NCBITaxon:176297 - Maize streak virus (MSV)
NCBITaxon:176297 - Maize tassel abortion virus (MTAV)
NCBITaxon:176297 - Maize vein enation virus (MVEV)
NCBITaxon:176297 - Maize wallaby ear virus (MWEV)
NCBITaxon:176297 - Maize white leaf virus
NCBITaxon:176297 - Maize white line mosaic virus (MWLMV)
```

You can see that the pathogens are all different viruses, but they are all being mapped to "Zea mays/Colletotrichum graminicola mixed EST library"

**Comment by jhpoelen** [comment]
Thanks for sharing. In the most recent scape at https://build.berkeleybop.org/job/extract-apsnet-diseases/92/artifact/apsnet.tsv . I found a single entry using NCBITaxon:176297 , namely Maize rough dwarf virus (MRDV)  . Can you confirm?

**Comment by austinmeier** [comment]
Confirmed.  Although even this strikes me as strange.  The name of that row is "Maize rough dwarf", with a `pathogen_label` of "maize rough dwarf virus (MRDV)"  This exact name shows up in several other rows (eg: row-10076), and in these other rows, the NCBItaxon is correctly mapped to `NCBITaxon:10989` (Maize rough dwarf virus)

**Comment by jhpoelen** [comment]
Sounds like we need an additional mapping from ```maize rough dwarf virus (MRDV)``` to ```NCBITaxon:10989```. Would you like me to add that?
