### ISSUE TITLE
Trait name/descriptor label from GRIN scrape

### ISSUE THREAD

**Issue by austinmeier** [jhpoelen/samara#9]
We would love to have included in the output a column including the descriptor name.  Perhaps between 'descriptor id'	'descriptor definition'. 

Example: https://npgsweb.ars-grin.gov/gringlobal/descriptordetail.aspx?id=68104
Returns
descriptor ID = 68104
descriptor definition = In-vitro dry matter disappearance (ivdmd) expressed as a percent of the cultivar venal. Higher than 100% suggests low digestibility & higher by-pass protein.

but lacks the actual descriptor name: By pass protein (PROTBYPASS)

Again, if this is not clear, let me know.
Thanks!

**Comment by jhpoelen** [comment]
now, the descriptor name is included in the resulting tsv file.

The lines below were extracted after implementing the feature. Please observe the value ```Core subset (CORE)``` in the lines: the name of the descriptor used.

```tsv
taxon id	taxon name	descriptor id	descriptor name	descriptor definition	method id	method name	observed value	accession id	accession number	accession name
300359	Medicago sativa L. subsp. sativa	68104	Core subset (CORE)	In-vitro dry matter disappearance (ivdmd) expressed as a percent of the cultivar venal.  Higher than 100% suggests low digestibility & higher by-pass protein.	391002	ALFALFA.PROTBYPASS.93.VOLENEC	140	1140225	PI 162787	'PAMPA'
300359	Medicago sativa L. subsp. sativa	68102	Core subset (CORE)	Crude protein in the leaf.	490600	ALFALFA.1989.BARNES	29.4	1140225	PI 162787	'PAMPA'
```
